// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYdDW2mxyZgD0ECDVcDfPJ6yX56j8TY0g',
    appId: '1:176170743812:web:fc7fc5041fa3d3172bdd51',
    messagingSenderId: '176170743812',
    projectId: 'loginproject-3a03a',
    authDomain: 'loginproject-3a03a.firebaseapp.com',
    storageBucket: 'loginproject-3a03a.firebasestorage.app',
    measurementId: 'G-4BEPFKFG90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASZMt_PmVOPQV3obk0i1-vD5xAUEWAR1s',
    appId: '1:176170743812:android:bc5a174dfe5493ba2bdd51',
    messagingSenderId: '176170743812',
    projectId: 'loginproject-3a03a',
    storageBucket: 'loginproject-3a03a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9kZUCs_SrM5aXDdq8MQUQZeoShvlasN8',
    appId: '1:176170743812:ios:46709280109ee1a42bdd51',
    messagingSenderId: '176170743812',
    projectId: 'loginproject-3a03a',
    storageBucket: 'loginproject-3a03a.firebasestorage.app',
    androidClientId: '176170743812-ehp3h4t32n6fnjr4610r7rlkj8mk5vqo.apps.googleusercontent.com',
    iosClientId: '176170743812-7npdfu1mtv5j860sbvrsh7rqg5qgjlko.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9kZUCs_SrM5aXDdq8MQUQZeoShvlasN8',
    appId: '1:176170743812:ios:46709280109ee1a42bdd51',
    messagingSenderId: '176170743812',
    projectId: 'loginproject-3a03a',
    storageBucket: 'loginproject-3a03a.firebasestorage.app',
    androidClientId: '176170743812-ehp3h4t32n6fnjr4610r7rlkj8mk5vqo.apps.googleusercontent.com',
    iosClientId: '176170743812-7npdfu1mtv5j860sbvrsh7rqg5qgjlko.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYdDW2mxyZgD0ECDVcDfPJ6yX56j8TY0g',
    appId: '1:176170743812:web:f4a76419db930e632bdd51',
    messagingSenderId: '176170743812',
    projectId: 'loginproject-3a03a',
    authDomain: 'loginproject-3a03a.firebaseapp.com',
    storageBucket: 'loginproject-3a03a.firebasestorage.app',
    measurementId: 'G-D16Q9D07B3',
  );

}